### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Masterxv** [Cryental/LeonaFXL-Free#1]
1>CSC : error CS2001: Source file 'C:\Users\Ethan\Desktop\LeonaFXL-Free-master\C# Client\Source Code\LeonaFXLP\NUniqueHardwareID.cs' could not be found.

**Comment by Masterxv** [comment]
web files without index.php

**Comment by Cryental** [comment]
NUniqueHardwareID is included in LeonaFXL.cs. 
I don't support this project anymore, please use https://github.com/Cryental/Keycipher.NET
